### ISSUE TITLE
M5stack Fire

### ISSUE THREAD

**Issue by TheDireHavok** [armel/ICSMeter#25]
is there a way to compile this to upload and run on the M5stack fire board?  I tried all I know (which is very little for VSC)  Any help would be great.

**Comment by armel** [comment]
Hi,

As the documentation says, the ICSMeter works perfectly on M5Stack Fire. Nothing special to do, except follow the documentation / watch the tutorial videos (watch links in the documentation). 

73 de F4HWN.

**Comment by TheDireHavok** [comment]
Thank you for responding, as it turned out. Had to reinstall Driver and it
loaded fine.

Have you had any luck with stack auto reconnecting to IC705 BT after a
shutdown? Have to manually connect each time. I have entered BT address of
705 and even tried entering BT address assigned to meter after pairing.

**Comment by armel** [comment]
Ok, fine.

About Bluetooth, according to the documention, you need to add the BD address of you IC-705 (enter Menu and go to Set > Bluetooth Set > Bluetooth Device Information) in your src/settings.h

The very first time, you need to do a manual pairing between your M5Stack and your IC-705. This is necessary. Couldn't do it any other way. 

But after that, if you shutdown your M5Stack, it must reconnect automaticaly, without any action on the IC-705.

73 de F4HWN.

**Comment by TheDireHavok** [comment]
I went into 705 BT settings and entered that address in src/settings.h,
This is what I entered, I had to enter each of the "#define xxxxx"
manually. Everything after shown is unchanged. The BT address shown is what
is already default in 705. Let me know if it looks OK.  It all seems to be
working fine aside from it auto connecting.. gonna try now to reflash it.

// IC Config
// For each line,
//  - IC Model (705, 7300 or 9700),
#define IC_Model 705

//  - CI_V Address (0x94 by default on IC-7300, 0xA4 by default on IC-705),
#define CI_V ADDRESS 0xA4

//  - IC Connect (USB or BT),
#define IC_CONNECT BT

//  - Serial Device (if USB) or BT Address (if BT with IC-705)
#define BT Address "30:31:7D:34:2A:01"
const char *choiceConfig[] = {
    "7300", "0x94", "USB", "/dev/ttyUSB0",
     "705", "0xA4", "USB", "/dev/ttyACM0",
     "705", "0xA4", "BT",  "30:31:7D:33:B2:58"
};

**Comment by armel** [comment]
No no and no.
Code is not magic.
Don't change the settings structure and don't create new constants...
By default, there is this code :

const char *choiceConfig[] = {
    "7300", "0x94", "USB", "/dev/ttyUSB0",     
     "705", "0xA4", "USB", "/dev/ttyACM0",    
     "705", "0xA4", "BT",  "30:31:7D:33:B2:58" 
};

Suppose your IC-705 BT address is 01:02:03:04:05:06, so do this change : 

const char *choiceConfig[] = {
    "7300", "0x94", "USB", "/dev/ttyUSB0",     
     "705", "0xA4", "USB", "/dev/ttyACM0",    
     "705", "0xA4", "BT",  "**01:02:03:04:05:06**" 
};

That's all.

73 de F4HWN.

**Comment by TheDireHavok** [comment]
It worked. TY Armel. Worked like a charm
